server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: order
          uri: http://order-service:8083
          predicates:
            - Path=/order/**

        - id: inventory
          uri: http://inventory-service:8082
          predicates:
            - Path=/inventory/**